NordicSemiconductor/IOS-nRF-Connect-Device-Manager

- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/ImageManager.swift
It looks like the logic was mostly OK, but there were variable-shadowing problems, since there were two variables named the same, one local and the other instanced, causing the mismatch between logs and logic. Looks okay now.
> Fix for always uploading Image 0

- Source/Extensions/String+McuManager.swift
- Source/Managers/BasicManager.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/ImageManager.swift
- Source/McuManager.swift
- Source/McuMgrLogDelegate.swift
- Source/McuMgrResponse.swift
We've now decided to put development into 'master', making it easier for pull requests and releases to be made.
> Merge 'Develop' branch into 'master'

- McuManager.podspec
Fixed some fields, bumped SwiftCBOR dependency version to 0.4.4.
> McuManager Podspec Update

- Example/Example/Base.lproj/Main.storyboard
Changes to the About Screen for the 1.1 update.
> About screen

- README.md
> Added Badges to README.md

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
- README.md
- Source/Managers/ConfigManager.swift
- Source/Managers/CrashManager.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/DefaultManager.swift
- Source/Managers/ImageManager.swift
- Source/Managers/LogManager.swift
- Source/Managers/RunTestManager.swift
- Source/Managers/StatsManager.swift
- Source/McuManager.swift
- iOSMcuManagerLibrary.podspec
- Fix for SMP Reassembly if Device is not connected prior to DFU Start
- Fixed Pause / Resume crashing
- Fixed Pause / Resume not working
- Code Cleanup
> Version 1.2.1

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
> Fix for incorrect speed calculation if DFU Upload is paused

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
> Fixed 'imageSize' String in both Basic and Advanced modes

- Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Note, however, that this does not set the SMP Reassembly Buffer Size for Advanced Upload.
> In Advanced Mode, 'Read' Command now also attempts to read McuMgr Parameters

- Example/Example/Util/McuMgrPackage.swift
This PR changes the way how the image hashes are displayed in Image Upgrade and Image Upload cards by adding 3 last bytes.
> Displaying 3 additional bytes of image hash

- Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
- Source/McuMgrManifest.swift
Now it is properly accessible.
Also, McuMgrManifest now also reads image and loadAddress.
> Moved McuMgrManifest to the iOSMcuMgrLibrary

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
I noticed this earlier today, but priority was in testing the reported Issue on GitHub rather than this User Interface nuance. But, before I forget I decided to fix it.
> Fix: In Advanced Mode, Buffers, Alignment and Chunks would remain Enabled during DFU Upload

- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/ImageManager.swift
Adds minimum check for watchOS so the library can be used on watches.
> add min watchOS check

- Source/Bluetooth/McuMgrBleTransportWriteState.swift
This is to make the logic of the code easier to read / find. But I think this is the culprit behind some timeout issues, since it's the logic that opens up the lock holding back the upper layers of Data processing.
> Refactor: 'Chunk Complete' Logic in McuMgrBleTransportWriteState moved to its own Function

- Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
- Source/Bluetooth/McuMgrBleTransport.swift
- Source/Bluetooth/McuMgrBleTransportWriteState.swift
- Source/McuMgrTransport.swift
These are changes I made whilst chasing the previous commit. But I think they warrant staying.
> Small Changes, Assertions and More Descriptive Errors

- Example/Example/View Controllers/Manager/DeviceController.swift
Reassembly is the last resort, instead of being set by default. Echo first attempts to send everything, then if there's an error corrects MTU Size, just like ImageController, and lastly, if all else fails, Reassembly is attempted.
> Added Reassembly Support for DeviceController 'Echo'

- Source/Bluetooth/McuMgrBleTransport.swift
Helpful addition if one doesn't want to be counting hex.
> McuMgrBleTransport write logs now adds byte count

- Source/McuMgrImage.swift
This should allow users to better understand what can be done to address the issue.
> Improved 'Magic Number' Error Descriptions

- Example/PrivacyInfo.xcprivacy
- Source/PrivacyInfo.xcprivacy
These are not necessary yet, but if we can get ahead of the curve, we should.
> Added Privacy Manifest for both library and Example App

- Source/Managers/DefaultManager.swift
- Source/McuMgrResponse.swift
This includes their responses as well, of course.
> Added Missing Commands (Application Info + Bootloader Info)

- Source/McuMgrManifest.swift
This adds both slot information, available to all Manifest(s) (slot 0 is assumed if not specified in the .json) and whether the Manifest targets Direct XIP.
> Support for Parsing Direct XIP Manifest Files

- Source/Managers/DFU/FirmwareUpgradeManager.swift
I can't do all of this at once. There's too much code, and it's quite a mess. I need to make sense of it.
> Small List Callback Refactor in FirmwareUpgradeManager

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
Logs here are more important than for ImageManager.
> Added more Logs to FirmwareUpgradeManager

- Source/Managers/DFU/FirmwareUpgradeManager.swift
This fixes two Confirm Loops, actually. The code was not written expecting having to send a 'Confirm' to Slot zero, so that caused issues. Then, when that was addressed, there was an infinite loop, but now because after uploaded to 0-1, 0-0, with 0.0 Active, if we try to confirm 0-1, it doesn't return that it has been Confirmed in the response, sending us into an infinite loop. So we mark it as confirmed after we send the command. If there is an error, anyway, the callback should catch it and return the Error.
> Fix for Confirm Loop

- Source/McuManager.swift
- Source/McuMgrImage.swift
This was... missing. Ouch.
As for the minor changes, yes. They should be on their own commit, but given that we're trying to turn things around in a short amount of time, I'd rather have them in when I remember we need them, than forget about it.
> Fix: Added 'Protected' TLV Magic Number + Other Minor Changes

- README.md
- Source/Managers/SettingsManager.swift
- Source/McuManager.swift
- Source/McuMgrLogDelegate.swift
This Manager Group ID has been officially renamed in SMP Specification. We also added missing error codes specific to this group.
> ConfigManager is now SettingsManager

- Source/Managers/FileSystemManager.swift
- Source/Managers/ImageManager.swift
Just trying to make 1.4 as complete as possible.
> Added Missing Error Codes

- Source/Managers/FileSystemManager.swift
Well at least I think this is the last one.
> Missing line for successful build with Xcode 14.2

- Source/Managers/DFU/FirmwareUpgradeManager.swift
A version of this was written, but commented out for 1.4's release since 'standard behaviour' dictates that firmware should not behave like the sample code we have that does and that causes this issue. Regardless, we think it's a good thing to deal with it because of how important DFU is.
> DirectXIP Confirm Loop Fix

- Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
As McuMgr params (buffer count and size) are now shown on the Device Status pane, they are not needed in the Images section. This PR removes the call.
> Reading McuMgrParams removed from Images details

- Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
- Source/Bluetooth/McuMgrBleTransport.swift
- Source/Bluetooth/McuMgrBleTransportWriteState.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/DefaultManager.swift
- Source/Managers/FileSystemManager.swift
- Source/Managers/ImageManager.swift
- Source/McuMgrResponse.swift
Xcode 15 finally (!) can spell-check code.
> Typos fixed

- Source/Managers/DFU/FirmwareUpgradeManager.swift
> Fix for Loop on Test Image 0 Slot 0 since it never switches flag to 'Tested'

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/Util/UIColor.swift
- Example/Example/View Controllers/Manager/DeviceController.swift
- Example/Example/View Controllers/Manager/FileDownloadViewController.swift
- Example/Example/View Controllers/Manager/FileUploadViewController.swift
- Example/Example/View Controllers/Manager/FilesController.swift
- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
- Example/Example/View Controllers/Manager/ImageController.swift
- Example/Example/View Controllers/Manager/LogsStatsController.swift
- Example/Example/View Controllers/Manager/SettingsViewController.swift
- Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
- Example/Example/View Controllers/Scanner/ScannerViewController.swift
This PR fixes a lot of issues in the nRF Connect Device Manager app. Mainly UI related.
The inner view controllers were redesigned and look more modern, have working constraints and automatic resizing on content change.
> UI improvements

- README.md
- Source/Managers/DFU/FirmwareUpgradeManager.swift
This was missing from the original 1.4 release.
> No Revert (.uploadOnly) FirmwareUpgradeMode

- Source/Managers/DFU/FirmwareUpgradeManager.swift
When discarding the Images we need to 'forget about' for the rest of our logic, mostly thanks to DirectXIP, we also discard everything we learn. This causes issues for non-DirectXIP DFU, because we forget if something has been uploaded, tested, etc.
> Fix for losing Response Image Info

- Source/McuManager.swift
We can just call upon minimum and maximum UInt8 values to get the correct ones.
> Nitpick: UInt8 have .min and .max values, so no need to hardcode them

- Example/Example/View Controllers/Manager/FileUploadViewController.swift
This is important in the context of our changes to support SMP Reassembly & Pipelining for File Upload. (For Download it doesn't make sense.)
> FileUploadViewController now shows Upload Speed

- Example/Example/Info.plist
- Example/Example/Util/McuMgrPackage.swift
- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- McuMgrSuitEnvelope.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/ImageManager.swift
This breaks API compatibility, so it requires build to be bumped up to 1.5. Since we need to release this ASAP, and there's no time for me to properly test writing against this API in nRF Connect, we will release the app but not release library updates. This will wait, and presumably be released as 1.5.1 if changes are required. I tried to add ".suit" file specifically, but it does not work. So I had to open up the DocumentController to allow any file to be selected, which we can correct later.
> SUIT (Software Update for Internet of Things) Support

- Example/Example/AppDelegate.swift
- Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
- Source/Bluetooth/McuMgrBleTransport.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/McuManager.swift
- Source/McuMgrLogDelegate.swift
- Source/McuMgrROBBuffer.swift
This PR improves logging in the library:
* A new optional method to specify minimum log level.
* Most log messages were improved, some had log level modified.
* nRF Connect Device Manager app will log only messages on level `.info` or higher. In debug all messages are logged.
> Log improvements

- README.md
> Updated README Documentation for SUIT

- Source/McuMgrImage.swift
Protected TLVs were not supported, leading to crashes. This was not an omission on our part, we just had no idea these were a thing needed to be supported.
> Added Support for McuMgrImage Protected TLVs

- Source/Managers/ShellManager.swift
- Source/McuManager.swift
- Source/McuMgrLogDelegate.swift
- Source/McuMgrResponse.swift
New ShellManager class has been added.
> Preliminary Support for McuMgr Shell over BLE

- README.md
- Source/Managers/DFU/FirmwareUpgradeManager.swift
There have been changes to the library that have rendered some of the text in the README as outdated.
> README Update

- Source/Bluetooth/McuMgrBleTransportWriteState.swift
- Source/Managers/SuitManager.swift
- Source/McuMgrResponse.swift
We need better firmware to continue this implementation. We can't do much more. Waiting for more feedback.
> Initial Polling Implementation

- Source/McuMgrManifest.swift
I'm not happy with everything here - mostly the loadAddress having to be zeroed-out and that the image was not added in the SUIT Manifest export by the firmware team. But, we have to make the best out of what we have. So that's what I tried here.
> Extended McuMgrManifest to support SUIT Changes

- Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
Since there will be big API Changes / Additions, a minor version change is required.
> Version Bump to 1.7

- Example/Example/Util/McuMgrPackage.swift
- Example/Example/Util/UTI.swift
- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/DFU/SuitManifestManager.swift
- Source/Managers/ImageManager.swift
- Source/Managers/SuitManager.swift
- Source/McuMgrResponse.swift
- Source/McuMgrSuitEnvelope.swift
For the first time, the library can now respond to "polling" requests. But there's more work to be done here.
> (In-Progress) End-to-end SUIT Polling Support

- Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
- Source/McuMgrPackage.swift
- Source/Utils/UTI.swift
This should seriously simplify and improve our upload API.
> Change: McuMgrPackage is now part of iOSMcuMgrLibrary

- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/SuitManager.swift
I mean, in theory this should work. Time and multiple more SUIT uploads shall confirm if it's true.
> Fix: No more Polling after Success

- README.md
If we make something better every day, even if only a little, the world becomes a better place overall.
> Small README Improvements

- Source/McuMgrPackage.swift
> Minor one line change

- README.md
Since our API has changed, the README must also be updated in unison before a release.
> Big README Update

- Source/Managers/SuitManager.swift
A McuMgrResponse needs a valid Header to be able to be printed a debug description.
> Fix for bad Suit List Response

- Source/McuMgrResponse.swift
This is to make it easier to surface information in the UI after making a (SUIT) List Request. Which I kind of don't know yet exactly what it does nor what it informs us about - but I hope that when I do, we don't have to modify the API too much.
> Added CustomStringConvertible & Codable Conformance to multiple types

- Source/Managers/SuitManager.swift
- Source/McuMgrResponse.swift
This is an improvement, mostly due to nRF Connect's insistence in actually using the APIs we write over here. Who is that guy, by the way? So annoying.
> Added Manifest "Roles" to SuitListResponse

- Source/Managers/SuitManager.swift
We still need to build using Xcode 14.2. Yes, you read that right.
> Changes to publish updated Pod

- Example/Podfile.lock
- iOSMcuManagerLibrary.podspec
Maybe this helps pod trunk update finally use the correct pod.
> Extended Podspec Supported Swift Versions

- iOSMcuManagerLibrary.podspec
I needed another change in the Pod's hex to be able to do pod trunk push. (Don't get me started. Yes, I want to get rid of CocoaPods.)
> Podspec Summary Update

- .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
- Package.resolved
- Package.swift
This PR attempts to resolve a missing package from release 1.7
Close: #251
> Resolve missing package: ZIPFoundation

- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/SuitManager.swift
- Source/McuManager.swift
(Badum... tsss!)
We all need to have our fun somehow, don't we? ;)
> Fix: A couple of 'unsupported' error codes were... unsupported

- Package.resolved
- Package.swift
+ iOS Minimum Deployment raised to iOS 12
+ Updated SwiftCBOR version to 0.4.7
> Updated SPM to match Cocoapods

- Example/Example/Util/StringConvertibles.swift
- Source/Utils/CBOR+String.swift
Hopefully everyone's upgrading to Xcode 16, because these warnings I think might break in 15 and lower.
> Fixed Xcode 16 Warnings

- Example/Example/View Controllers/Scanner/ScannerViewController.swift
I just saw this code and thought I had to improve it, even if it was just a little bit.
> Minor ScannerViewController Code Cleanup

- Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
- Source/Managers/SuitManager.swift
After a SUIT Envelope or Image has been uploaded with "defer Install" to delay processing, this 'Confirm' Command can be sent to trigger processing.
> Implement 'Confirm' Equivalent of SUIT, which triggers Envelope Processing

- Source/Managers/SuitManager.swift
There are two independent implementations for calculating a packet's payload, one for the packet itself, and the other to calculate the packet header's size for each offset, to allow us to calculate then how much Data we can put in to fit within our MTU bounds. This meant that every time we need to alter the payload, we'd have to remember to modify this twice. And it has not happened once, nor twice, that I've missed the second place where the payload is calculated. It's time to put a remedy to this ongoing situation.
> Fix for Duplicate Payload Building Implementation(s)

- Source/Managers/DFU/FirmwareUpgradeManager.swift
Some devices will run SUIT but under an McuBoot Bootloader, which means we still need to support sending all the SUIT Images, including the Envelope and the Caches, through ImageManager (McuBoot).
> Added Support for SUIT through McuBoot

- Source/Managers/ImageManager.swift
Suit Manager needed SUIT. Instead of copying the relevant code, we broke it off into a new component, made it resusable, used it to implement pipelining for SUIT, and now we're bringing it back to ImageManager (Mcuboot).
> Backport of New McuMgrUploadPipeline into ImageManager

- Source/Managers/SuitManager.swift
Basically, we don't need to return the expected return offset from upload(data:deferInstall:at:). We can calculate it instead, and have a cleaner API. Not fun to have this kind of code duplication but I guess it's the best we can do right now.
> Minor internal SuitManager Change

- Source/Managers/ImageManager.swift
This brings it up to par with "Disabled" Number of Buffers.
> Fix: Byte Alignment "disabled" is now "Disabled"

- Example/Example/View Controllers/Manager/FilesController.swift
- Example/Example/View Controllers/Manager/ImageController.swift
> Fix for 'Image' Advanced Bar Button Item not being accessible after opening 'Files'

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
- Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Does not change anything regarding what the code does, but it's one of those things worth cleaning up.
> Fix: Removed Unnecessary Force-Unwrap(s)

- Source/Managers/DFU/FirmwareUpgradeManager.swift
- Source/Managers/SuitManager.swift
I mean, this should be 'preliminary' or 'presumed' feature. But I guess we'll figure out if it doesn't work the way we always do.
> Added Support for Pause / Resume / Cancel on SUIT Uploads

- Example/Example/View Controllers/Manager/BaseViewController.swift
> Fixed UITabBar shade of Blue

- Source/Managers/SuitManager.swift
Direct Cancel worked. But Cancelling after Pausing did not work.
> Fix: Allow Cancel with Paused Upload

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Estimated Swap Time, Number of Buffers, Byte Alignment and Erase App Settings are now stored in User Defaults for 'Basic' Mode.
> Update: Restore Basic Settings

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
> User Defaults Keys

- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Similarly to Basic Mode, we're now storing the Chunk Size, Byte Alignment and Pipeline Depth for Advanced Mode as well.
> Update: Restore Advanced Settings

- Source/Managers/DefaultManager.swift
- Source/McuMgrResponse.swift
It's a very good thing that we wrote this code thinking it might be expanded in the future, without actually knowing in any way if that was going to be the case. Really surprised, in a good way of course.
> Added Support to request Bootloader Active Slot

- Package.resolved
- Package.swift
Outdated SwiftCBOR package url updated
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/issues/305
> #305 SwiftCBOR package repository url updated

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/View Controllers/Manager/BaseViewController.swift
- Example/Example/View Controllers/Manager/DeviceController.swift
- Example/Example/View Controllers/Manager/FilesController.swift
- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/ImageController.swift
- Example/Example/View Controllers/Manager/LogsStatsController.swift
In Basic Mode, we now support ZIP files with multiple bootloader images. This change also adds "Bootloader Slot" to the Device Status list.
> Added support in "Basic" Mode for MCUboot Bootloader Update

- Source/Managers/ImageManager.swift
- Source/McuMgrResponse.swift
We also deleted the previous "eraseState" API, since it was invalid.
> Implemented McuMgrInfo slotInfo Command

- Source/Managers/DefaultManager.swift
Some added Error definitions that were added to Zephyr but that we hadn't caught on with.
> Added Missing OS / Default Group Errors

- Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
The Cancel button in Advanced Mode does not work as expected. Now it's much closer.
> Fix for Advanced 'Cancel' Button

- Source/Managers/DFU/FirmwareUpgradeManager.swift
This override is designed to make SUIT over MCUBoot work seamlessly, but it turns out we're just overriding the Upgrade Mode all the time if it's ever set to 'Upload Only'. So now, we only override the Upgrade Mode if we detect that the content that we're sending is SUIT over MCUBoot Bootloader.
> Fix for Incorrect Upgrade Mode Override for 'Upload Only'

- Source/Bluetooth/McuMgrBleROBWriteBuffer.swift
Since we have measured the cutouts, we've never seen more than about 6ms. The previous, like, three releases ago, version waited for about 15ms. That seemed to be a good ballpark; so what we're doing, is ignoring it. Filip does the same, and it doesn't appear to get Mesh app hurt. But Filip's strategy is the reverse, which is to send something, and wait for "peripheralIsReady()" callback. That's an option we could pursue, flipping the logic around. Potentially less speed, I think. But we can keep that idea on the back of our minds.
Anway, I cannot properly test this change because... CoreBluetooth. Or Bluetooth. I don't... anymore.
> Fix: Override Peripheral Is Not Ready For Write Without Response

- Source/Bluetooth/McuMgrBleTransport.swift
- feat (McuMgrBleTransport.swift): refactor the constructors so that the CBPeripheral constructor will set the mtu directly
The new mechanism doesn't require the peripheral to be rediscovered when the CBPeripheral is being provided directly to the constructor
Note that based on the tests we conducted the auto-configured mtu value (20) works when uploading firmware however:
(1) it is slow (4/5 kb/sec as opposed to 10+ kb/sec with 1.9.0)
and (2) if the firmware is cached then we get an error about the mtu being out of range when the native library tries to simply swap firmwares
These issues are not covered by this PR because they are out of scope (I thought to mention them however for the sake of completeness).
Our workaround was to set the mtu value for the file-uploading to 57 (anything …
> #337 [1.9.2] Fix: FirmwareUpgradeManager.start() fails with an error about the 'mtu' value even though it used to work just fine with 1.9.0 

- Source/Managers/FileSystemManager.swift
Found the tested snippet of code mentioned previously.
> Added casting for specific FileSystemManagerError

- Source/Managers/FileSystemManager.swift
McuMgrParameters is now a lot more prevalent than a couple of years ago. And it can provide a lot of essential information to guarantee correct FileSystemManager procedures.
> Added McuMgrParameters step to FileSystemManager

- Example/Example/View Controllers/Manager/LogsStatsController.swift
Making things look better helps finding issues.
> Cleanup of LogStatsController

- README.md
I learn things, and I try to make the README reflect them.
> File Download Reassembly Correction

- Source/Managers/FileSystemManager.swift
The recommended upload(name:data:using:delegate:) API uses the legacy API, but setting it up beforehand. For users of the legacy API directly, no @uploadConfiguration property is set, leading to a crash. This change aims to address both issues, as well as improve documentation.
This was reported in GitHub here: https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/issues/208
> Fix: Report missing upload configuration when using legacy upload(name:data:offset:callback:) API directly instead of crashing

- Source/Managers/DFU/FirmwareUpgradeManager.swift
As of this writing, a reset into bootloader mode is required for firmware upload. So, we make it more explicit. Also mirroring the robot version of this library.
> Report Invalid Bootloader Mode Error for Bare Metal Firmware

- Source/Managers/FileSystemManager.swift
I think the proper need here is to connect to the target Peripheral and then get the appropriate DFU. This is just a patch, but not the intended "good behaviour".
> Deleted Unnecessary SMP_SVR_BT_L2CAP_MTU Constant

- Example/Podfile
- Example/Podfile.lock
- Package.swift
- iOSOtaLibrary/LICENSE
- iOSOtaLibrary/Source/OTAManager.swift
- iOSOtaLibrary/iOSOtaLibrary.podspec
- iOSOtaLibrary/iOSOtaLibrary.xcodeproj/project.pbxproj
- iOSOtaLibrary/iOSOtaLibrary.xcodeproj/project.xcworkspace/contents.xcworkspacedata
We're adding complementary libraries to the existing iOSMcuManagerLibrary Package. So, there will be the existing iOSMcuManagerLibrary, as well as other libraries. They are intended to be used independently; together if needed, or one without the other. Hopefully. If I'm setting up things right.
> Initial setup for iOSOtaLibrary

- README.md
Again, making things better a step at a time adds to a lot in the long(er) run.
> Added Cocoapods to README next to SPM Version

- Example/nRF Connect Device Manager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iOSOtaLibrary/Source/Network/GetFirmwareRequest.swift
- iOSOtaLibrary/Source/OTAManager+Tokens.swift
- iOSOtaLibrary/Source/OTAManager.swift
- iOSOtaLibrary/Source/Tokens/ProjectKey.swift
- iOSOtaLibrary/iOSOtaLibrary.xcodeproj/project.pbxproj
Tried to get iOS-Common-Lib backported down to iOS 13... not easy. Shaders need to be skipped, which is doable, but Logger requires version 14.
> In-Development: Preparing for OTAManager Network Request

- Example/Example/View Controllers/Manager/BaseViewController.swift
- Example/nRF Connect Device Manager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iOSOtaLibrary/Source/Network/GetFirmwareRequest.swift
- iOSOtaLibrary/Source/Network/HTTPRequest.swift
- iOSOtaLibrary/Source/Network/Network.swift
- iOSOtaLibrary/Source/Network/URLSession.swift
- iOSOtaLibrary/Source/OTAManager.swift
The API is not finalised yet of course. But the Network request is being made. Networking code shamelessly stolen from myself from iOS-Common-Lib.
> In-Progress: Attempt at requesting Latest Firmware

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/View Controllers/Manager/BaseViewController.swift
- Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
- Example/Example/View Controllers/Manager/ImageController.swift
- iOSOtaLibrary/Source/Network/GetLatestReleaseInfoRequest.swift
- iOSOtaLibrary/Source/OTAManager.swift
We can now request latest firmware from nRF Cloud / Memfault, Download it via iOSOtaLibrary, get a local temporary URL, and give it to iOSMcuMgrLibrary to flash.
> Added "Check for [nRF Cloud] Updates to Basic Image / FirmwareUpgradeController

- Example/Example/View Controllers/Manager/DeviceController.swift
- Example/Example/View Controllers/Manager/FilesController.swift
- Example/Example/View Controllers/Manager/ImageController.swift
I missed earlier this cleanup step.
> Code Cleanup in observabilityStatusChanged callbacks

- Example/Example/View Controllers/Scanner/ScannerViewController.swift
Yeah... I should've done this a long time ago when it became clear I was the responsible one. But also, why didn't the original developers do this? Doesn't matter. What's important is that it's in there, now. Users will hopefully appreciate it. I know I will.
> Fix: ScannerViewController now supports Pull-to-Refresh

- Example/Example/View Controllers/Scanner/ScannerViewController.swift
Everything's in the details. Details matter.
> Added "Pull-to-refresh" footer in ScannerViewController
