Source/Extensions/String+McuManager.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift
Source/McuMgrResponse.swift

`FirmwareUpgradeManager` has a new API to receive multiple images to upload, and we are now also reading the `image` field for `McuMgrImageStateResponse`'s `ImageSlot`, giving it a default value of zero to not break compatibility with firmware that doesn't report this field. Also added some cleanup.

Preliminary Multi-Image Support FirmwareUpgradeManager

---

Source/Managers/BasicManager.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuManager.swift
Source/McuMgrLogDelegate.swift

This is implemented via the new BasicManager, belonging to a new group, which should be extended in the future as its capabilities grow. For now, it's only used for the 'eraseAppSettings' command, which is enabled by default.

Added Support for 'Erase App Settings' Command

---

Package.swift

The problem is SwiftCBOR has upped their minimum version to iOS 10, but we still want to support iOS 9, so we've changed our dependency to match version 0.4.4, which is the last version supporting iOS 9.

Fix: SwiftCBOR dependency was tied to 'master'

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

When implementing this library in my own project, I found that if I ran the Firmware Upgrade Manager in testAndConfirm mode, it would do everything properly up until the last step, where instead of marking the state as successful it would just throw itself into an infinite loop of resetting and confirming the firmware.
Changing the self.reset() call to a self.success() call, mimicking FirmwareUpgradeManager's reconnect function fixes this problem.
(Re-submitting from a separate branch so that I can continue to use the master branch on my fork.)

 Infinite Confirm/Reset loop when running in testAndConfirm mode.

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

This was all prompted by a Pull Request by a user. And yes, we did do the check to see that with reset(), after successful reconnection a success() call is sent up through the API ranks.

Fix: .confirmOnly requires reset() call, but .testAndConfirm requires success() call at the end of Confirm Callback

---

Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift

Image Slot Selection has also been extended past App Core and Net Core, to Image 2 and Image 3, because some devices might not announce they have multiple image slots / cores, but the user should have total control of this.

Change: When there is no manifest, Advanced Mode now allows Image Slot Selection

---

Source/Managers/ImageManager.swift

Sending it as 'application' was considered too obnoxious.

Fix: "Uploading..." Logs message is now sent as .debug

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

Only Image 0 was being confirmed, leading to reset (swaps) where the Net Core or Image 1 was not CONFIRMED / PERMANENT, or whatever was needed.

Fix: Image 1 was not being confirmed

---

Example/Podfile.lock
Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift

This PR improves logging (by removing unnecessary logs) and fixes a bug causing an endless confirm loop when the image is in "pending" state (that is a TEST command was sent for it). Now, when unable to confirm the image, the library will reset the device. This will make the device to restart with the new (or old firmware) and a new DFU operation can be performed to update the device again.

Improvements

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

Bug was caused by starting a muilti-image DFU Upload wherein the images were in the wrong order. The for-loop inside confirmationCallback expects self.image[j] to match j, otherwise we might mark the incorrect image as confirmed but skip over the one that is not confirmed in the loop itself (guard statement checking our own properties whether an image is confirmed). This extends further into test and validate stages, where we also made some changes to the code.

Fix for Confirmation-Loop Bug when Starting Multi-Image DFU with unsorted Image(s)

---

Example/Podfile.lock
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

This PR fixes several issues in the DFU manager:
- Makes sure, that the device does not reset before all images are uploaded and tested/confirmed
- Fixes `start` method, which didn't match the sample app
- Improves logging, and providing validation results as logs
Besides, the PR improves some Swift grammar here and there and rearranges callbacks for better readability.

DFU and logs improvements

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

This PR fixes the endless loop happening when the same image is in both primary and secondary slot of an image.
In #55 (and before) the flags of each image in the `images` property in DFU manager were modified multiple times. 
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/blob/bab7cba94ec1944f99461a8f1a19ca9dcf552d65/Source/Managers/DFU/FirmwareUpgradeManager.swift#L353-L370
However, as `FirmwareUpgradeImage` is a `struct`, each modification is effectively replacing the image object with a new struct. The following call to `markAs...(_ image:)` was not finding the image instance, and returning, without changing the flag.
The image, in the above case, was marked as uploaded, but not as confirmed or tested, thus the library tried to test it again. As it was already …

Fix for situation where the same image is in both slots

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

The latter is a consequence of making the former Codable.

Codable conformance for FirmwareUpgradeConfiguration and ImageUploadAlignment

---

Example/Example/Util/McuMgrPackage.swift

This means it is exposed to any library user.

McuMgrPackage is now Marked as Public

---

Example/Example/Util/McuMgrPackage.swift

A change to the McuMgrLibrary would not allow the Example App to build.

Fixed Build Issue

---

Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift
iOSMcuManagerLibrary.podspec

What we wanted to fix is the 'Missed ACK' issue which was just 'silenced' before. Now we think we have a proper / logic-level fix, but unfortunately, it looks like our zealous attempt at implementing 'fast timeout' like Android has, might've broken more things. At least that's what our constant back-and-forth which changes show, fast timeout was maybe 'too fast' under our testing, and it worked for periods of time when additional debugging code slowed it down.

1.2.4 Version

---

Source/Bluetooth/McuMgrBleTransport+CBCentralManagerDelegate.swift
Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
Source/Bluetooth/McuMgrBleTransport.swift

When SMP Reassembly is enabled, the firmware needs to 'chunk' the Data on the other side and send it to us. The Sender is not obliged to include the header

Fix: Don't expect Sequence Number in all Data packet responses

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift

It makes sense for it to be there. And the code changes to make it happen weren't big. In fact, most of the changes were on the Sample App, proving the point.

Small Refactor: @estimatedSwapTime is now a part of FirmwareUpgradeConfiguration

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

This concerns the following issue:
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/issues/69
The cyclic reference is released too fast so upgradeDidComplete will never fire.

Release cyclic reference after upgradeDidComplete

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

To make it easier to keep track of how important calls to this function is, I renamed it so it's clear when using it that it does objc_sync calls by itself to guarantee mutual exclusion and no crashes. Or at least it hopes.

Private setState() FirmwareUpgradeManager Rename

---

Source/Managers/ImageManager.swift
Source/McuManager.swift

Previously, only ImageManager was handling sequence numbers, and that too, only for upload. All other issued commands / writes defaulted to sequence number zero. I think a possible cause for issues in the validated / timeout stage was that when issuing commands that were not the upload, we were going back to sequence number zero. And they might've been dropped / confused by the rest of the code. Now they're integrated within McuManager, so they're used for all commands. This required deeper changes into the ImageManager logic, but I think we might've solved a couple of previous issues.
Maybe.

Unified Sequence Number(s): McuManager now tracks Sequence Numbers and rotates them for every single command/write/send

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Bluetooth/McuMgrBleTransportWriteState.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift

Previously, calls to send()' command in McuManager were not returned in-order. They were returned as they were returned by CoreBluetooth, leaving the re-ordering to higher-levels. But now, McuManager now buffers callbacks in case it detects a different Sequence Number it's not expecting, and keeps the results and the callbacks until it has enough stored results to return them in-order.

McuManager Sequence Number Callback Reordering

---

Example/Example/View Controllers/Manager/DeviceController.swift

If we select a Device, then send multiple messages from Device Tab, then go to Image and perform a DFU, it'd stall. It'd work with Pipelining Disabled, but not with Pipelining. I chased this issue to the ends of the Earth. In the end, I think what was happening is that the firmware / peripheral was not returning the messages because within the same connection, the Sequence Numbers were switching back from above zero to zero, because the connection is kept, but not the manager(s), which each track their own Sequence Number. So obviously if commands with, say, sequence numbers 0-7 were sent to and replied to, and then we start DFU with sequence number 0, obviously the firmware is not going to reply back.

Fix for failed DFU when first sending 'echo' messages from Device Tab

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Bluetooth/McuMgrBleTransportWriteState.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift
Source/McuMgrHeader.swift

We use 'sequenceNumber' so much that I think it makes sense to give its representation its own 'type'. Even if it's just an alias for UInt8.

McuSequenceNumber Typealias Type for UInt8

---

McuMgrROBBuffer.swift
Source/McuManager.swift

By pulling the re-order portion of the code into its own structure, and a struct as that as well, we discovered that the actual code was going on recursively, so reading / modifying the arrays without any form of locking. So we use DispatchQueue sync() now to protect this state. I think the speed will be a bit slower, but overall the code should be safer.

McuManager Re-Order Buffer is now its own Component

---

Example/Example/Util/McuMgrPackage.swift
Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Source/McuMgrManifest.swift

I noticed we had more information in the code than towards the user, which is not helpful when debugging issues. So now we've added some descriptions for common errors, and they're also exposed to the user.

Improved Error Reporting when Selecting DFU File

---

Example/Example/View Controllers/Manager/DeviceController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/FileSystemManager.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift

It's possible that setMTU() calls cause an infinite loop. And it's the same small piece of code that happens a couple of times in multiple managers, including the 'echo' command. And instead of patching it in five places, it's better to just make the code express itself better.

API Change: McuManager setMtu() can now throw, rather than return a Boolean

---

Source/Managers/BasicManager.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuMgrTransport.swift

Some firmware does not even reply back to the 'Erase App Settings' command, which was not being taken into account. So now we do, and if we get that specific error, we stop attempting to Erase App Settings directly and try to complete the DFU process as quickly as possible.

Fix: Erase App Settings does not Fail Fast Enough

---

Source/Bluetooth/McuMgrBleTransport.swift

The whole point of being able to set your timeout is that you can control how fast 'you fail'. If you want to fail really fast, but Wait and Retry doesn't let you, what's the point?

Fix: If your send() timeout is faster than the WAIT_AND_RETRY_INTERVAL, we lower the Wait and Retry Interval to said value

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

There's no point in sending an Erase App Settings Command if the firmware device is not going to reply back to it, which in turn leads to the Upload DFU to fail when it doesn't need to. Unfortunately at the moment we do not turn back the switch in the UI, but we do log the issue.

Fix: If Device Capabilities are not Supported, then Erase App Settings Isn't

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift

Without it, it was not visible exactly what the app / DFU was doing when the Erase App Settings caused the issue in older versions of firmware. That has been addressed of course, but still, improving visibility of what the app is doing is a good thing for now and the future.

Added 'Erase App Settings' as a FirmwareUpgradeState value

---

Source/Managers/BasicManager.swift
Source/Managers/DefaultManager.swift

There's a limit to the size of the echo message, which is 2475 bytes, package size (not payload - tested). If the message is over this limit, the firmware device will just not reply - wish the behaviour was different, but it's not. So, we provide a helpful error message that returns quickly rather than waiting for a timeout Error.

Fix: BasicManager's echo() returns an Error if the message is too long

---

Source/McuManager.swift

Source: https://docs.zephyrproject.org/3.2.0/services/device_mgmt/smp_protocol.html#status-error-codes-in-responses

Filled-in a missing McuManager Return Codes (RC)s and fixed 'Bad State' Error Description

---

Source/Managers/ImageManager.swift
Source/McuManager.swift

This is because writing a new Image might trigger an erase on the firmware side, which could take a few seconds. Also, note that even if we've set '20' seconds as the timeout number, the total timeout time will probably be closer to 60, because the BleTransport has 3 automatic retries unless an error is encountered.
Fixes Issue https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/issues/52#issuecomment-1479580347

Fix: When uploading offset 0 of any Image, we need to wait more before triggering a Timeout

---

Source/Managers/ImageManager.swift
Source/McuMgrResponse.swift

If it's present and it returns 'false', then we need to throw an error because we're not matching the offset the device is expecting.

Support for 'match' value in Image Upload Response

---

Source/McuManager.swift

When we updated the library to send the Full SHA, this ballooned the minimum size of the MTU, otherwise the packet is bigger than the MTU, so no Data can be sent. This we've seen as crashes out in the wild in nRF Connect.

Updated Minimum Valid MTU Size to 73 bytes

---

Source/Bluetooth/McuMgrBleTransport.swift

McuMgrBleTransport sets a connection lock with a timeout of 20 seconds, but then when it's time to wait for said lock, it waits for just a second, which might not be enough, causing a timeout, but then, the next time a packet is attempted (due to the min number of retries being larger than 1), the connection might be set because a bit more time was needed. This might mean the Mcu Mgr Parameters Request might fail just because the target firmware device was not super fast or BLE traffic was high.

Fix for invalid lock timeout on Connection when sending a Packet

---

Source/Managers/BasicManager.swift
Source/Managers/DefaultManager.swift
Source/Managers/ImageManager.swift
Source/McuManager.swift

Previously, the default wait time for commands was 1 second, which in theory should be enough, but on firmware devices under stress (older chips) it might be too strict. So we've doubled the amount. Which could make transfers slower when a retry is required, but we can't have it all.

Extended 'Fast Timeout' for Commands

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/McuManager.swift

Core Bluetooth has a buffer when we give it Data to send / write with the writeValue API. Each Device has a different limit, but after 10 packets for sure, could be more, the API stops 'adding' or accepting Data, and so doesn't send it. There are other solutions for this, like a proper API callback for when you can send. We opted for a 'spinlock' solution of checking and waiting whether we can send. But we don't do it packet by packet, because it's too slow and CoreBluetooth is going to tell us every time that we should wait. So instead, we set a target of 10 writes, we wait for as many Connection Intervals as is necessary, and then keep writing. We get decent speed I'd say, and previous working use cases for DFU should not be affected.

Fix: Wait for Write Without Response Buffer

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Extensions/Data+McuManager.swift
Source/Extensions/String+McuManager.swift

So, instead of reading incoming and outgoing bytes as 0x03000177 we show them as 0300 0177. I think this is easier to read and compare bytes when checking whether something is working as expected or not. It also matches how Apple's Packet Logger (Sniffer) Developer tool shows bytes.

Legibility change: We now log Data as two-byte spaced at Ble Transport Level

---

Source/Extensions/Data+McuManager.swift

It's not necessary for the Mcu Mgr Library per se, but it can be useful for customers of the library. nRF Connect, for example.

Added Reverse Endianness Hex Decoding Option

---

Source/McuManager.swift

It was still being reconigised as an error, of course. But now we have a specific case for it as well as a proper description for the user.

Implemented McuMgr Return Code 11 Description

---

Example/Example/Util/McuMgrPackage.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

Before Direct XIP, active slot was always assumed to be 0, or Primary. And upload or target slot was always 1, or Secondary. That's not the case, so we need a way to track which slot is the target. This represents ongoing work.

Internal Structures Support for targeting specific Image Slot

---

Source/McuMgrManifest.swift

The default slot should be 1, aka "secondary". Because except for DirectXIP, we always upload to the Secondary slot when doing DFU.

Fix for bad default 'slot' value

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift
Source/McuMgrManifest.swift
Source/McuMgrResponse.swift

This commit represents the first time we were able to upload Direct XIP without having to stop the debugger, check something, modify something in the code, etc. Now, this doesn't mean that it's finished - I believe it can be made a lot tidier. But it's closer.
As for the revert on the Default Image Slot value, if we leave Direct XIP aside, what we want every time is for the image to be in slot 0. That's what our comparison for 'is this already uploaded?' is against. Hence, why the correct value, I think now after going back and forth a couple of times, is zero for how we've been doing things up until now.

Initial Direct XIP Support + Revert of Default Image Slot Value (back to 0)

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuMgrResponse.swift

Just trying to familiarise myself with the code again after a recent break, and trying to tighten up some bits of code a bit more. Although I can't think of an alternative to the embedded for in LIST to mark the other Slot for the same Image as Uploaded, which is executed twice. Other than checking that's not marked as Uploaded, of course.

Minor Changes

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

It's helpful to know, if there is an Image that can be uploaded to either Slot, which one was selected.

Added Target Slot Information in Logs

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

This becomes more necessary now, since we can't make assumptions regarding what happens after, such as which specific Image needs to be sent the Confirm Command.

Fix: FirmwareUpgradeManager does not track Uploaded Images

---

Example/Example/View Controllers/Manager/FileDownloadViewController.swift
Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Source/Managers/BasicManager.swift
Source/Managers/ConfigManager.swift
Source/Managers/CrashManager.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/DefaultManager.swift
Source/Managers/FileSystemManager.swift
Source/Managers/ImageManager.swift
Source/Managers/LogManager.swift
Source/Managers/RunTestManager.swift
Source/Managers/StatsManager.swift
Source/McuManager.swift
Source/McuMgrHeader.swift
Source/McuMgrManifest.swift
Source/McuMgrResponse.swift

In SMPv2, now only is the Request SMP Version part of the Header now, but also Groups are allowed to return their own specific Errors. To make the API as smooth (https://www.youtube.com/watch?v=4TYv2PhG89A) as possible, without breaking too many things but also making use of the language, we made the response return a Result<>, since that's what it was designed to do in cases where one must check whether there's an error or a success scenario. We made our own custom error enum that can bridge both types of error, the precious McuMgr "RC" values and all the new Errors dependant on the Request's Group ID. Not all Groups are supported, I tried to add the Errors for the Groups we already have some semblance of support for. And as usual for a change this big, there will be errors and issues. …

Added Support for SMPv2 Errors

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

Either, Both or none could be present. If one fails, there's no relation to the other, as we were assuming previously.

Fix: McuMgr Parameters & Bootloader Info are Independent

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/FileSystemManager.swift

We need to make the Cocoapod build using Xcode 14.2 tools because with newer versions it breaks. So we cannot use newer features. (This Is Why We Can't Have Nice Things.)

Fixes for Xcode 14.2 build tools

---

Source/Managers/FileSystemManager.swift
Source/McuMgrLogDelegate.swift
Source/McuMgrResponse.swift

These were missing from the previous release of iOS-McuMgrLibrary. Also, interesting wrinkle here: none of this is tested :( So, if you're swearing at this code via git-blame yes, blame me. I wrote a full frontend to implement and test Pipelining for FS Upload, but I'm not doing that for these.

Added status, crc32, sha256 and closeAll APIs to FileSystemManager

---

Source/Managers/DefaultManager.swift

The implementation to get the name of the Bootloader is weird, but that's not on us.

Added 'Name' as possible query for BootloaderInfo

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

So basically, we won't upload the inactive Slot and try to run from it like we would before. If either slot 0 or 1 has a matching hash to our Image, in DirectXIP (which has 2 hashes for 2 slots), we declare it successful. The way we implemented this is not the most elegant way, but it works. That's the important part.

DirectXIP Upload is now Successful if either Slot Hash Matches

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

This is during the handover process between FirmwareUpgradeManager to ImageManager. When the first gives the second the set of images that are needed to be sent. It doesn't fix anything, it's just for me to help me understand I'm not losing my mind.

Logs now log which Image/Slot/Hash Combination is scheduled to upload

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

The 'if' was basically a pit into hell of throwing an Error. My God did I have to go far to chase this one.

Fix: Bad Confirm Callback Logic affecting Multi-Image DFU

---

Source/McuManager.swift
Source/McuMgrROBBuffer.swift

By raising this Log up the food chain, apps using the library can see the information logged by this low-level component.  I needed to see this to debug the Amazon Sidewalk template we're chasing.

McuMgr ROB (Re-Order) Buffer can now Log Directly

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

Previously we were disabling two of those, but not pipelining. Which in most cases, did not cause any issue. But sometimes it could, specially with devices running firmware built with older SDKs.

Fix: If McuMgr Parameters are not supported, disable Pipelining/Reassembly/Erase App Settings

---

Source/McuManager.swift
Source/McuMgrROBBuffer.swift

The ROB (Re-Order Buffer) now effectively returns back values when it's not missing the intervening numbers. This should speed-up DFU speed in situations where sequence numbers are returned out of order. It could be argued this is not necessary and that the need for re-ordering responses is indeed a red-herring for other DFU Library issues, which is why the Buffer can now log. So if the ROB Buffer is indeed reordering responses, they should be visible on the logs, hence providing information about a potential cause for an issue.

BLE Transport Layer Re-Order Buffer Improvements

---

Source/McuManager.swift

If it exists, why don't we use it?
Source: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/advancedoperators/#Value-Overflow

Use of native Swift Overflow Operator to rotate Sequence Numbers

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

This PR removes overriding user configuration when Mcu Manager Params command is not supported by the device. Apparently, some devices don't support this command, but still allow for pipelining making the DFU much faster.
If the user wants 6 buffers, let's try to use 6 buffers.
For the current nRF54 implementation (which does not support Mcu Mgr Params) the speed increase is 7Kb/s to 40 kB/s (Pixel 7 with Android 14 achieved top speed 71 kB/s with 6 buffers).

Don't override user settings when Mcu Manager Params are not supported

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift

This PR fixes the following issues:
* Allows sending SUIT file from Advanced view on Inage tab. Before it was only possible to send using the Basic view.
* Adds option to select 7 or 8 Mcu Mgr Buffers in both Basic and Advanced view.
* Alignment is printed correctly.
* Byte alignment is not required with pipelining enabled. A validation for that was removed.

Allowing sending SUIT files from Image/Advanced

---

Example/Example/Info.plist

A warning was shown when submitting the app to AppStore without this flag.

A flag added to Info.plist that the app supports opening files in place

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Source/McuMgrSuitEnvelope.swift

The hash part is a bit complicated, so we've made the API better from the library user's perspective. We were on the fence regarding making the modes 'public' and so on, but these things can change specially since SUIT is under heavy development. So if we need to, we can open it up later.

Streamlining of start() API for McuMgrSuitEnvelope

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift

It was not easy to find how to allow .suit files. Then we stumbled into it by accident, and it looks stable across multiple apps, so we're keeping it.

Fix: When selecting a file for DFU, we now only show supported types, like before

---

Source/McuMgrImage.swift

The offset here was off by one, and wrong. We're trying to do the right thing here.

Fix for bad offset in McuMgrImageTlvTrailerEntry

---

Source/McuMgrImage.swift

We read the value correctly (we think) but the size of the Tlv Trailer Data is 4 bytes, so we need to skip one byte in between.

Fix for a bad Fix for McuMgrImage Tlv Trailer Offset

---

Example/Example/Util/StringConvertibles.swift
Example/Example/View Controllers/Manager/BaseViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuMgrResponse.swift
Source/McuMgrSuitEnvelope.swift
Source/McuMgrSuitManifest.swift

There's more functionality that needs to be built upon parsing the bootloader's name. This is just a start. And as for the McuMgrSuitManifest, we'd really like to implement a full parser, but this is as far as we got before we had to move on. So for now, it's not marked as Public.

SUIT Bootloader Introduction + Internal-use only McuMgrSuitManifest

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/DFU/SuitManifestManager.swift
Source/Managers/SuitManager.swift
Source/McuMgrResponse.swift

We need to first make a request for the manifest, which has all of the roles, and then we need to ask for each role one after the other. So all of this was moved out of FirmwareUpgradeManager.

New SuitManifestManager to request full State Response for all Roles

---

Example/nRF Connect Device Manager.xcodeproj/project.pbxproj

This is for the script that updates the Build Number. It's a Patch rather than a Fix, but whenever I've tried something else to go for this, then it didn't update when it was needed so, better just run it every time.

Patch to Remove "Always Running Script" Xcode Issue

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/DFU/SuitManifestManager.swift
Source/McuMgrResponse.swift

We don't have an active use for these yet, we're working on the implementation side. But this was needed so that we could write the code that asks the API user for the resources requested by the Device's Firmware.

SuitFirmwareUpgradeDelegate + Resource API Introduction

---

Source/McuMgrManifest.swift

And also, we reduced the text for "Unknown". It's possible I have more user-facing uses for this description that I previously thought. This is why it's helpful to write applications against your own APIs.

Manifest File ContentType is now Codable

---

Example/Example/Util/McuMgrPackage.swift
Source/McuMgrManifest.swift
Source/McuMgrSuitEnvelope.swift
Source/McuMgrSuitManifest.swift

So, for SUIT Zip Packages, we do not care about the other files. We only look for the SUIT Envelope in the Manifest, and that file has a hash, or a digest we can sink our teeth onto, and then we can proceed with SUIT. But again, this is just one small step.

McuMgrPackage now parses a SUIT Manifest .ZIP

---

Example/Podfile
Example/Podfile.lock
iOSMcuManagerLibrary.podspec

Previously, it was an 'Example' App Dependency.

Change: ZIPFoundation is now a iOSMcuMgrLibrary Dependency

---

README.md

I think, with the advent of Swift 6, a lot of people are going to be asking whether an API is "Swift 6 or not" so, it makes sense to have this listed at the top.

Swift Version added as Badge to README

---

Example/Example/View Controllers/Manager/FileUploadViewController.swift
Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
Source/McuManager.swift

Xcode warnings panel is now fully clean. Nothing to see here. So we're a good iOS citizen.

Fixed all Xcode Warnings

---

Source/McuMgrPackage.swift

This I think, is not an issue on iOS. But it is on macOS, where the Caches Directory returned by the API is not Application-specific, but shared. So if we clean it out and then unzip there, we're essentially deleting stuff we don't own. Also, like it happened in nRF Connect, we might be deleting the same file we want to DFU !

Fix: McuMgrPackage no longer considers itself the owner of your Caches Directory

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Source/Managers/DFU/FirmwareUpgradeController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/SuitManager.swift
Source/McuMgrPackage.swift
Source/McuMgrResponse.swift

So, if you're a user of the API, you need a way, when you get the SUIT Delegate Callback, to provide the Data. Most API users, we assume, will keep their reference to the Upgrade Manager of their own, as is the case of the Example App. But, if you don't and you might be using the Delegate's API's returned protocol FirmwareUpgradeController, you might need a way to provide your resource there. So if we expanded the Controller's API to support this. I also had the thought of killing this 'Controller' protocol since it's mostly the FirmwareUpgradeManager itself. But, I thought giving us more API flexibility in the future might be a good idea.

FirmwareUpgradeController API Expansion

---

Source/McuMgrPackage.swift

Unfortunately this is a regression. We were too overzealous with trying to reduce code, and we messed up here. Glad our time spent in testing so many DFU attempts shed some light into this.

Fix for Bad Multi-Image Parsing

---

Source/Managers/SuitManager.swift
Source/McuMgrResponse.swift

For SuitManager's list, we now return a subtype of McuMgrResponse. This keeps the API in line with all the others. As for why this was not the case originally, it's because this API is not simple. We need to send one call, and build the response out of other responses. So there's no 'one McuMgrResponse' that we can return, so we build it instead. Hopefully we built it well.

SuitListResponse

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/SuitManager.swift
Source/McuManager.swift
Source/McuMgrResponse.swift

Previosuly, it was the raw unsigned integer value. This could backfire in ways I can't foresee, but the intention here is to make the value of the numbers more explicit, so we can write better code. (Please don't backfire too much.)

API Change: McuMgrResponse's @rc property is now a McuMgrReturnCode enum

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

When attempting to test and confirm a device that had previously had test only run against it we encountered an issue where the library would not confirm the image and instead just reported success.
This patch handles the case when we are in test and confirm mode and there are no images to test but there are still images to confirm.

fix(dfu): handle case where device is already in test mode 

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

So, we might not get an error. We might not get an invalid / unsupported code, and yet, no values for bufferSize and bufferCount are returned, hence the crash. Better to adopt some defensive programming.

Crash Fix for nil McuMgr Parameters Response

---

Source/Extensions/Data+McuManager.swift

We flagged the _send() function in McuMgrBleTransport as being responsible for increase in memory pressure when performing DFU. And the culprit, was appending Strings. We don't do enough complicated Strings in the _send() function itself, except, that we log all the bytes that we send. And we send a lot of bytes in a very small amount of time, so this optimization makes sense here.

Optimization: Reduced Memory Pressure by autoreleasing generated Strings in hexEncodedString()

---

Example/Example/View Controllers/Scanner/ScannerViewController.swift

This is an attempt to allow users to update already-connected devices. Primarily HID devices such as Keyboards and Mice.

Change: Retrieve Connected Peripherals advertising SMP Service on Scan Start

---

Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Source/McuMgrResponse.swift

Instead of showing the result of the pre-existing ImageManager's 'LIST' Command, we now parse the SUIT roles and state.

Initial Implementation of 'LIST' Command for SUIT Bootloader

---

Source/McuMgrManifest.swift

We can't change the behaviour of DFU if we can't detect there's a cache file as part of the envelope.

Added Detection of SUIT Cache Files in McuMgrManifest

---

Source/Managers/ImageManager.swift

We are missing key metadata regarding whether a Suit update involves cache files, which significantly alter the steps required in order to perform the update. Hence, this additive API change was deemed the best option at this stage.

Change: ImageManager.Image now adds @content property in preparation for SUIT updates involving cache files

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift
Source/Managers/SuitManager.swift
Source/McuMgrManifest.swift
Source/McuMgrSuitEnvelope.swift

The procedure has now been slightly altered. If Image(s) with .suitCache content is detected for upload, we will send the "defer_install" flag, finish uploading the Envelope, proceed uploading all Cache Images, send the equivalent "Confirm" command, and then poll in case any additional resources are requested. At the moment, polling is not supported by existing firmware, but it may be in the future.

Added Support for SUIT 'Cache' Image Upload & Deferred Install(s)

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuMgrPackage.swift

This is because cache(s), or SUIT Cache(s), are actually Image(s) that also need to be uploaded. Furthermore, in the case where the McuBoot Bootloader is used to Upload SUIT, this maps beautifully as well considering they target different partitions or 'images'. So it's both a code and a logic  / design win.

Chance: McuMgrPackage Image(s) now includes 'caches'

---

Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift

Before this change, the cell containing the text of the 'Read' / 'List' Command for example would grow in size, but never update when the displayed text shrank, so you could end up with blank space everywhere except in the middle of the screen. This is a brute force approach, but oh well.

Fix: Length of Advanced Commands Text is now refreshed on Update

---

Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Example/Example/View Controllers/Manager/Widgets/McuMgrViewController.swift
Source/Managers/ImageManager.swift
Source/McuMgrPackage.swift

We need to allow, in 'Advanced' Mode, for the user to select multiple .bin files and do the update themselves. This means, we want to allow the user to select to which Partition they'd like to send the .bin file. We hacked this earlier, making a single .bin destined for SUIT to show up as multiple 'Image's. Which is... a hack. So we decided to put the hacky code somewhere else that makes more sense, which is in the UI. This has led to other API changes, primarily the code to get the 'name' of an Image.

Fix to allow Partition Selection in Advanced Mode only for SUIT

---

Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/SuitManager.swift
Source/McuMgrUploadPipeline.swift

This is Multiple Buffers, not Reassembly, which adds larger buffer sizes than MTU. The implementation is mostly a copy of the ImageManager logic handling pipelining, but we 'extracted' it to try and make it reusable, and used it in SuitManager.

Added Pipeline (Multiple Buffers) Support into SUIT

---

Example/Example/View Controllers/Manager/BaseViewController.swift

We can't properly test for devices older than 15, but we think majority of use cases, or users, will fall within this category. In any case, we've made the UITabBar more readable in both Light and Dark modes. Crazy to think Dark Mode was introduced back in 2019...

Improved Readability of TabBar in iOS 15 or higher

---

Example/Example/View Controllers/Manager/ImageController.swift

In Advanced Mode, with a File Selected and if we perform a Read / List command and the output is fairly long, when switching between tabs the UI might look like a stretched barcode at times. This is due to the blunt instrument that is 'reloadData' applied on the UITableView. This is a fractional improvement.

"Barcode" Issue Improvement

---

Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift

If in 'Advanced' Mode, you re-uploaded the same file, the displayed update speed would be incorrect, since it would not reset the upload information.

Fix for Advanced Re-Upload Speed

---

Source/Managers/DFU/FirmwareUpgradeManager.swift

By default, Erase App Settings is enabled due to it being preferred for McuBoot updates. But SUIT can return an error which could result in the user getting an Error code when the SUIT update was successful.

Fix: Don't send Erase App Settings to SUIT Bootloader

---

Source/Managers/FileSystemManager.swift

Raised via GitHub Issue here: https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/issues/297

Fix: FileSystemManager's closeAll() op should be 'write' instead of 'read'

---

Source/McuMgrManifest.swift

We're just adding the enum value here, not implementing the bootloader update (yet). Also, do not confuse the "content" to be an mcuboot [bootloader] with the bootloader being mcuboot. Though presumably they should be, if the content is an mcuboot bootloader.

Added "mcuboot" ContentType

---

README.md

"Bootloader" update is not part of McuMgrPackage API. It has to be done "by hand".

Minor Readme change

---

Source/Managers/SettingsManager.swift

From https://docs.zephyrproject.org/latest/services/device_mgmt/smp_groups/smp_group_3.html#write-setting-request, settings write should be a bstr.
This would match the behaviour for Android
(https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/blob/94becd03c88a7acfc164db2cea5fe80bdd3106e4/mcumgr-core/src/main/java/io/runtime/mcumgr/managers/SettingsManager.java#L175-L181)

Correct Settings write value CBOR type

---

Example/Example/View Controllers/Intro/IntroViewController.swift
Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/ImageManager.swift

The minimum version was raised to iOS 12 and equivalent, so these are not needed anymore. We kept one, as a reference for MTU size(s) of past versions.

Deleted unnecessary #available(s)

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Bluetooth/McuMgrBleTransportWriteState.swift

We can convert this API call into a 'sync' instead of 'async'. But in general, we should prefer 'async' calls instead of 'sync'. There's a reason why we went the 'sync' reason here which is, I presume, if there's an error we want to stop immediately and not do unnecessary work. We will do more testing to confirm whether this breaks anything or not.

Change: McuMgrBleTransportWriteState now has an open() API for Error(s)

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/Managers/FileSystemManager.swift
Source/Managers/ImageManager.swift
Source/Managers/SuitManager.swift
Source/McuManager.swift
Source/McuMgrTransport.swift

The way we understand it at the moment, CoreBluetooth has an underlying buffer that accumulates all the Data passed to it via cbPeripheral "write" API calls. If we exceed this buffer, the Data passed-in to it is just lost. When we think we might hit this limit, we stop and ask the CBPeripheral if we think we can start writing again. Problem is, this almost always happens, as we have the code written now, in the middle of a buffer write. And the stall is for so long, that the firmware starts thinking we wrote the chunk of Data already. It's a mess. There are levers in the current API to fix this, like reducing the number of buffers, reassembly size, etc. But we want to keep the library / API more reliable, hence the nature of this change.

Change: Limit Reassembly Buffer Size to fall within CoreBluetooth API Buffer

---

Source/Managers/ImageManager.swift

If we receive a lower offset, we might trigger the library to send Data it's already sent, which throws us in a loop we don't need to be in.

Fix for out-of-order Response(s) not allowing offset to grow

---

Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/ImageManager.swift

It turns out, there was a callback to properly implement "backing off" behaviour and give time to CoreBluetooth / Transport layer to be ready to send more Data. This change significantly improved upload speed stability as well as a myriad of other related issues.

Fix for Throughput Issues when CBPeripheral is not ready for Write Without Response

---

Source/Managers/ImageManager.swift

It makes sense to want to cancel an upload directly instead of having to pause it first.

Fix for 'Cancel' Button in Basic Mode not working unless Paused first

---

Source/Extensions/Data+McuManager.swift

Attempt at optimisation by telling the output String what its expected size should be. This way, it should set up a backing buffer of the specified size instead of being surprised as the size of the String increases via append() calls.

Minor change to hexEncodedString()

---

Source/Extensions/String+McuManager.swift

For-loops are more efficient than for-Each. We're also setting the size of the output String beforehand, to try to avoid new memory allocations.

Fix for String API to insert a separator

---

Example/Example/View Controllers/Manager/Widgets/ImagesViewController.swift
Source/McuMgrResponse.swift

From NCS 2.9.0 onwardss, MCUBoot supports sending Compressed Images.

Initial Support for NCS v2.9 "Compressed" Flag

---

Source/McuMgrPackage.swift

We need to find the manifest by looking for "manifest.json" instead of by looking for the first "json" file.

Fix for ZIP Package containing multiple ".json" files

---

Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift

One init declared 'throws', but it was unnecessary since there were no try statements inside. Removing said throws showed a chain reaction of unnecessary try(s) and other throws, which removing them caused further changes. Should be a welcome change.

Removed chain of unnecessary "throws"

---

Source/McuMgrResponse.swift

- SettingsManager.read response is decoded as byte array instead of a utf8 string.

Fixed SettingsManager.read response incorrectly mapped from CBOR string instead of byte string.

---

Source/Bluetooth/McuMgrBleROBWriteBuffer.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift

There are more changes here. For example, we no longer "order" or "reorder" enqueued writes by their sequence number. Because if we do so, we're going to mix writes from different Managers, because sequence numbers are random. So, the last "write" might have a lower sequence number than the first, but it might get reordered into being at the head of the window (queue). Trying to keep CPU ROB Buffer terminologies here.
Besides that, we no longer wait to get a write for a specific sequence number in order to perform a write. We just send all writes within the window until we hit the dreaded "peripheral is not ready" flag. And, we also addressed a possible issue of peripheralIsReady() getting an enqueued call, but then the enqueue() getting called first, and finding the flag in "ready" and …

Change: Always attempt to empty WriteROBBuffer "Window" on Writes

---

Source/Bluetooth/McuMgrBleROBWriteBuffer.swift

The recent release broke macOS compilation, this fixes it.

Fix McuMgrBleROBWriteBuffer.swift on macOS

---

Source/Managers/FileSystemManager.swift

Some errors from the Filesystem Group, such as errors when writing to a file, etc. need to be read correctly via their Group RC code, instead of defaulting to the standard McuMgr Error Group. Otherwise, the cause of a failure might not be understood correctly. Like, "Error Code 8" means "Busy, Try Later" in Standard but is actually "Write Failed" for Filesystem.
"Attempted" because I could replicate the error last night, but lost the code in a Git mishap, and now I can't replicate it.

Attempted Support for Group-Specific Errors in FileSystemManager

---

Example/Example/View Controllers/Manager/FileUploadViewController.swift
Source/Managers/FileSystemManager.swift
Source/Managers/ImageManager.swift

So, it was possible to enable pipelining via FirmwareUpgradeConfiguration 'configuration' argument. But it was not implemented, so no speed improvement or changing in behaviour would occur. Now, it is enabled internally via the same McuMgrUploadPipeline, shared with ImageManager and SuitManager. Preliminary tests show it working as expected, but FileSystemManager is complicated to test due to the small external flash storage availability. But we're here to solve issues.

Preliminary (as in, we'd be surprised if there are no issues) support for Pipelining in FileSystemManager

---

Example/Example/View Controllers/Manager/BaseViewController.swift
Example/Example/View Controllers/Scanner/ScannerViewController.swift
Source/Bluetooth/McuMgrBleTransport+CBCentralManagerDelegate.swift
Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
Source/Bluetooth/McuMgrBleTransport.swift
Source/Bluetooth/UuidConfig.swift

- Created `UuidConfig` class to open up the Bluetooth transport to dynamic UUIDs. This mimics the [Android](https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/blob/main/mcumgr-ble/src/main/java/io/runtime/mcumgr/ble/UuidConfig.java) implementation.
- Created a `DefaultMcuMgrUuidConfig` that replaces the constants `McuMgrBleTransportConstant.SMP_SERVICE` and `McuMgrBleTransportConstant.SMP_CHARACTERISTIC`.

Dynamic bluetooth UUIDs

---

README.md
Source/Managers/DFU/FirmwareUpgradeManager.swift
Source/McuMgrResponse.swift

This is not an automatic update. Reset into Firmware Loader mode is needed. Then going back, reconnecting to the device, and sending the application .bin file.

Initial NCS Bare Metal Firmware Update Support

---

Source/Bluetooth/McuMgrBleTransport.swift
Source/Managers/DFU/FirmwareUpgradeManager.swift

This explains why making independent API calls, such as an echo or a single mcuMgrParameters before a full-DFU looked smoother, it's because there was a delay that allowed the transport to get a valid MTU value after an active connection was established. Now we check at the lowest level; I attempted to throw an "invalid MTU" value but I think it caused too many issues. Doing it here is sneaky, but it's also the Transport's responsibility? Anyway, things should work better now.

Fix: McuMgrBleTransport now checks if current MTU is valid after Connection (Result)Lock

---

Example/Example/View Controllers/Manager/BaseViewController.swift
Example/Example/View Controllers/Manager/DeviceController.swift
Example/Example/View Controllers/Manager/FileDownloadViewController.swift
Example/Example/View Controllers/Manager/FileUploadViewController.swift
Example/Example/View Controllers/Manager/FirmwareUpgradeViewController.swift
Example/Example/View Controllers/Manager/FirmwareUploadViewController.swift
Example/Example/View Controllers/Manager/LogsStatsController.swift

Previously, BaseViewController was firing simultaneous requests for mcumgr parameters and others in parallel to an app's operation, such as start DFU. This caused locking issues in the sense that, the transport was reused for DFU and BaseViewController requests, and the supposedly random sequence number was not so random so, different requests happened to land on the same internal 'lock' causing issues. We fixed that by moving the BaseVC to its own private transport, but we then learned that many firmware(s) will not accept these simultaneous requests, so we modified the app to "wait" for BaseVC's requests before making a big operation such as DFU or FileManager.

Fix: Wait for BaseViewController's deviceStatusInfo Requests

---

LICENSE
README.md

Because we moved it in the shuffle / reorg, of which we now have to do a new round of, the GitHub indicator linked from the README is broken. This restores it. I opted to copy it, so the McuMgrCocoapod retains its own copy as well, which is why it was moved there.

Restored LICENSE in main README file

---

Example/nRF Connect Device Manager.xcodeproj/project.pbxproj

Linking it once is enough. And no, this is not because of the OTALibrary - that has its own linking stage, which remains.

Fix for duplicate link against iOSMcuMgrLibrary

---

Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
iOSOtaLibrary/Source/OTA/OTAManager.swift

If the comparison fails, or the given Artifact's Hash can't be parsed, an OTAManagerError will be thrown.

Improvement: OTAManager's download(artifact:) now performs SHA256 Hash Comparison

---

Example/Example/Util/DeviceInfoManager.swift
Example/nRF Connect Device Manager.xcodeproj/project.pbxproj
Example/nRF Connect Device Manager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOSOtaLibrary/Source/Observability/ObservabilityManager+Internal.swift

The copy-pasted function awaitBleStart() made sense to add to the BLE-Library itself. So we did! It's now called isPoweredOn()

Update to latest iOS-BLE-Library

---

Example/Example/Util/DeviceInfoManager.swift
Example/nRF Connect Device Manager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

The peripheral.discoverServices() is now filtering as expected, so this change is to reflect that in the code.

Updated code to reflect fixed TODO
